Search bar Component
johnproodian/thyme pull request #24
Opened 2022-10-04 00:26 UTC by janayAl

2022-10-04 02:09 UTC, johnproodian requested changes
The pull request failed on the vercel build. Based on the errors Vercel gave, it looks like the issue is the div element on lines 24-26 in thyme-app/src/pages/LandingPage/index.js. That needs to either go inside the MDBContainer element or there needs to be <> </> tags that enclose all the elements of LandingPage.

2022-10-04 02:25 UTC, janayAl commented
Thank you! Both did the trick. When I put it inside of the MDBContainer the search bar is viewable but it's. underneath the sign-up area. So I placed it outside and added the <> around all the elements. It doesn't display now with it outside, but I'm assuming the search bar won't be on the landing page or could possibly be in the navbar. I'll be able to move it around once we all decide how everything will flow.

2022-10-24 19:59 UTC, johnproodian commented
> Thank you! Both did the trick. When I put it inside of the MDBContainer the search bar is viewable but it's. underneath the sign-up area. So I placed it outside and added the <> around all the elements. It doesn't display now with it outside, but I'm assuming the search bar won't be on the landing page or could possibly be in the navbar. I'll be able to move it around once we all decide how everything will flow.

Thanks for making those changes, Janay. Sorry I'm only getting to reviewing them now. There was a merge issue because I think both you and Iyan made changes to the landing page at the same time, so I thought one of you may have done a lot of work for nothing. But the only thing you really changed on the landing page was to add the searchbar to it. So I was able to take Iyan's styling changes and your searchBar addition (plus your <> additions) to make it work--I think. 

But I edited by hand, so I think someone has to approve my changes too.

2022-10-25 21:40 UTC, alizenguyen approved these changes

2022-11-09 02:55 UTC, alizenguyen approved these changes

2022-11-09 02:56 UTC, alizenguyen approved these changes

2022-11-09 02:56 UTC, johnproodian approved these changes

2022-11-09 02:56 UTC, merged